name: Java CI with Maven for deployment-examples

on:
  push:
    paths:
      - .github/workflows/mvn-deployment-examples.yaml
      - deployment-examples/**
  pull_request:
    paths:
      - .github/workflows/mvn-deployment-examples.yaml
      - deployment-examples/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Support longpaths
        if: matrix.os == 'windows-latest'
        run: git config --system core.longpaths true

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-deployment-examples-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v4
        with:
          repositories: '[{ "id": "redhat-ga-repository", "url": "https://maven.repository.redhat.com/ga" }]'
          plugin_repositories: '[{ "id": "redhat-ga-repository", "url": "https://maven.repository.redhat.com/ga" }]'

      - name: Run ShellCheck
        if: matrix.os == 'ubuntu-latest'
        uses: ludeeus/action-shellcheck@master
        with:
          ignore: bcgithook bdd-ui kogito-quick-start-workshop offliner-maven-plugin pam-eap-setup pam-vagrant rhpam-charts

# Example Mvn Build 
      # - name: Build deployment-examples/<NEW_PROJECT>
      #   run: |
      #     pushd deployment-examples/<NEW_PROJECT>
      #     mvn -B clean package --no-transfer-progress
      #     popd
